# Generated by Django 4.2.1 on 2024-10-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_transmission_choices_car_transmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Listing',
        ),
    ]
